"""冻结在看结果之前的规则。演示和测试都读这里，跑完不准改。"""

SEGMENTS = 20
PEAK_TOLERANCE = 1
MIN_VIDEOS = 2
MIN_ROWS = 5
TOP_CLAIMS = 8
MIN_CHARS = 2
MAX_CHARS = 30
BRIEFING_CLAIMS_PER_TYPE = 3
DIFF_ITEMS = 8
EVIDENCE_SAMPLE = 12
